const bands =   [ 

{   band: "AC/DC",
    albums: [
        ["T.N.T.",["hard rock","blues rock","rock and roll"],[],["rock","blues"],[9]], 
        ["Back In Black",["hard rock"],[],["rock"],[7.5]], 
        ["The Razors Edge",["hard rock"],[],["rock"],[5]], 
    ],get number() {return this.albums.length},land: "Australia",
}, 

{   band: "Black Sabbath",
    albums: [
        ["Black Sabbath",["heavy metal","acid rock","blues rock"],[],["metal","rock","blues"],[9]], 
        ["Paranoid",["heavy metal","doom metal","stoner metal"],["traditional doom","stoner doom","heavy/doom"],["metal"],[10]], 
        ["Master Of Reality",["heavy metal","doom metal","stoner metal"],["traditional doom","stoner doom","heavy/doom"],["metal"],[10]], 
        ["Vol 4",["heavy metal","stoner metal"],[],["metal"],[9]], 
        ["Sabbath Bloody Sabbath",["heavy metal","stoner metal"],[],["metal"],[9]], 
        ["Sabotage",["heavy metal","stoner metal"],[],["metal"],[9]], 
        ["Heaven And Hell",["heavy metal"],[],["metal"],[]], 
        ["13",["heavy metal","doom metal"],["traditional doom", "heavy/doom"],["metal"],[]], 
    ],get number() {return this.albums.length},land: "United Kingdom",
},
{   band: "Dream Theater",
    albums: [
        ["When Dream and Day Unite",["progressive metal"],[],["metal"],[]], 
        ["Images And Words",["progressive metal","progressive rock"],[],["metal","rock"],[10]], 
        ["Awake",["progressive metal","progressive rock"],[],["metal","rock"],[10]], 
        ["A Change Of Seassons",["progressive metal","progressive rock"],[],["metal","rock"],[]],
        ["Falling into Infinity",["progressive metal","progressive rock"],[],["metal","rock"],[]], 
        ["Metropolis Part II: Scenes From A Memory",["progressive metal","progressive rock"],[],["metal","rock"],[10]], 
        ["Six Degrees of Inner Turbulence",["progressive metal","progressive rock"],[],["metal","rock"],[8]], 
        ["Train Of Throughts",["progressive metal"],[],["metal"],[9]], 
        ["Octavarium",["progressive metal","progressive rock"],[],["metal","rock"],[9]], 
        ["Systematic Chaos",["progressive metal","progressive rock"],[],["metal","rock"],[7]], 
        ["Black Clouds & Silver Linings",["progressive metal","progressive rock"],[],["metal","rock"],[6]], 
        ["A Dramatic Turn of Events",["progressive metal","progressive rock"],[],["metal","rock"],[6.5]], 
        ["Dream Theater",["progressive metal","progressive rock"],[],["metal","rock"],[7]], 
        ["The Astonishing",["progressive metal","progressive rock"],[],["metal","rock"],[6]], 
        ["Distance over Time",["progressive metal","progressive rock"],[],["metal","rock"],[]], 
        ["A View from the Top of the World",["progressive metal","progressive rock"],[],["metal","rock"],[]], 
    ],get number() {return this.albums.length},land: "United States",
},
{   band: "Foo Fighters",
    albums: [
        ["Foo Fighters",["grunge","post-grunge","alternative rock"],[],["alternative"],[]],           
        ["The Colour and the Shape",["post-grunge","alternative rock"],[],["alternative"],[]],               
        ["One by One",["post-grunge","alternative rock"],[],["alternative"],[]],           
        ["Echoes, Silence, Patience & Grace",["post-grunge","alternative rock"],[],["alternative"],[]],           
        ["Wasting Light",["post-grunge","alternative rock","hard rock"],[],["alternative","rock"],[]],                   
        ["Sonic Highways",["post-grunge","alternative rock","hard rock"],[],["alternative","rock"],[]],                   
        ["Concrete and Gold",["post-grunge","alternative rock","hard rock","psychedelic rock"],[],["alternative","rock"],[]],                   
        ["Medicine at Midnight",["pop rock","alternative rock","post-grunge"],[],["pop","alternative"],[]],                   
    ],get number() {return this.albums.length},land: "United States",
},
{   band: "Helloween",
    albums: [
        ["Helloween",["speed metal","power metal"],["EU style power"],["metal"],[]],           
        ["Walls Of Jericho",["speed metal","power metal"],["EU style power"],["metal"],[]],           
        ["Keeper of the Seven Keys: Part I",["power metal"],["EU style power"],["metal",],[]],           
        ["Keeper of the Seven Keys: Part II",["power metal"],["EU style power"],["metal",],[]],           
    ],get number() {return this.albums.length},land: "Germany",
},
{   band: "Iron Maiden",
    albums: [
        ["Iron Maiden",["heavy metal"],[],["metal"],[]], 
        ["Number Of The Beast",["heavy metal"],[],["metal"],[]], 
        ["Piece Of Mind",["heavy metal"],[],["metal"],[]], 
        ["Powerslave",["heavy metal"],[],["metal"],[]], 
        ["Somewhere in Time",["heavy metal"],[],["metal"],[]], 
        ["Seventh Son of a Seventh Son",["heavy metal"],[],["metal"],[]], 
    ],get number() {return this.albums.length},land: "United Kingdom",
},
{   band: "John Coltrane",
    albums: [
        ["Blue Train",["hard bop"],[],["jazz/fusion"],[]], 
        ["Giant Steps",["post-bop","hard bop","bebop"],[],["jazz/fusion"],[10]], 
        ["My Favorite Things",["post-bop","hard bop"],[],["jazz/fusion"],[9]], 
        ["Impressions",["Avant-Garde Jazz","post-bop"],[],["jazz/fusion"],[]], 
        ["A Love Supreme",["post-bop"],[],["jazz/fusion"],[]], 
    ],get number() {return this.albums.length},land: "United States",
},
{   band: "Judas Priest",
    albums: [
        ["Rocka Rolla",["hard rock","blues rock"],[],["rock","blues"],[]], 
        ["Sad Wings of Destiny",["heavy metal"],[],["metal"],[9]], 
        ["British Steel",["heavy metal"],[],["metal"],[9]], 
        ["Screaming for Vengeance",["heavy metal"],[],["metal"],[7]], 
        ["Painkiller",["heavy metal","speed metal"],[],["metal"],[10]], 
    ],get number() {return this.albums.length},land: "United Kingdom",
},
{   band: "Metallica",
    albums: [
        ["Kill Em All",["speed metal","thrash metal"],["old school thrash"],["metal"],[8]],   
        ["Ride The Lightening",["thrash metal"],["old school thrash"],["metal"],[9]],    
        ["Master Of Puppets",["thrash metal"],["old school thrash"],["metal"],[8]],    
        ["And Justice For All",["thrash metal"],["old school thrash"],["metal"],[8]],    
        ["Black Album",["heavy metal","thrash metal"],[],["metal"],[7]],      
        ["Death Magnetic",["thrash metal"],["old school thrash"],["metal"],[6]],      
        ["hardwired",["thrash metal","heavy metal"],["old school thrash"],["metal"],[5]],      
    ],get number() {return this.albums.length},land: "United States",
},
{   band: "Nightwish",
    albums: [
        ["Wishmaster",["power metal","symphonic metal"],["symphonic power"],["metal"],[9]], 
        ["Dark Passion Play",["power metal","symphonic metal"],["symphonic power"],["metal"],[8.5]], 
        ["Imaginaerum",["power metal","symphonic metal"],["symphonic power"],["metal"],[]], 
    ],get number() {return this.albums.length},land: "Finland",
},
{   band: "Nirvana",
    albums: [
        ["Nevermind",["grunge","alternative rock"],[],["alternative"],[7]], 
    ],get number() {return this.albums.length},land: "United States",
},
{   band: "Opeth",
    albums: [
        ["Orchid",["death metal","progressive metal"],["progressive death","melodeath"],["metal"],[]], 
        ["Morningrise",["death metal","progressive metal","progressive rock"],["progressive death","melodeath"],["metal","rock"],[]], 
        ["My Arms, Your Hearse",["progressive metal","death metal","progressive rock"],["progressive death"],["metal","rock"],[9]], 
        ["Still Life",["progressive metal","death metal","progressive rock"],["progressive death"],["metal","rock"],[10]], 
        ["Blackwater Park",["progressive metal","death metal","progressive rock"],["progressive death"],["metal","rock"],[9.5]], 
        ["Deliverance",["progressive metal","death metal","progressive rock"],["progressive death"],["metal","rock"],[9]], 
        ["Damnation",["progressive rock"],[],["rock"],[10]], 
        ["Ghost Reveries",["progressive metal","death metal","progressive rock"],["progressive death"],["metal","rock"],[9]], 
        ["Watershed",["progressive rock","progressive metal","death metal"],["progressive death"],["metal","rock"],[]], 
    ],get number() {return this.albums.length},land: "Sweden",
},
{   band: "Overkill",
    albums: [
        ["Feel The Fire",["thrash metal","speed metal"],["old school thrash"],["metal"],[8.5]],   
        ["Taking Over",["thrash metal","speed metal"],["old school thrash"],["metal"],[8]],   
        ["Under the Influence",["thrash metal"],["old school thrash"],["metal"],[9]],   
        ["The Years of Decay",["thrash metal"],["old school thrash"],["metal"],[10]],   
        ["Horrorscope",["thrash metal"],["old school thrash"],["metal"],[9]],   
        ["I Hear Black",["thrash metal","groove metal"],[],["metal"],[8]],   
        ["W.F.O.",["thrash metal"],["old school thrash"],["metal"],[8.5]],   
        ["The Killing Kind",["thrash metal","groove metal"],[],["metal"],[]],  
        ["From the Underground and Below",["thrash metal","groove metal"],[],["metal"],[]],  
        ["Necroshine",["thrash metal","groove metal"],[],["metal"],[]],  
        ["Ironbound",["thrash metal"],["old school thrash"],["metal"],[9]],  
        ["The Electric Age",["thrash metal","speed metal"],["old school thrash"],["metal"],[8]],  
        ["The Wings of War",["thrash metal","speed metal"],["old school thrash"],["metal"],[7.5]],  
        ["Scorched",["thrash metal"],["old school thrash"],["metal"],[9]],  
    ],get number() {return this.albums.length},land: "United States",
},
{   band: "Rhapsody(Of Fire)",
    albums: [
        ["Legendary Tales",["power metal","symphonic metal","progressive metal","neoclassical metal"],["symphonic power","progressive power"],["metal"],[9]], 
        ["Symphony of Enchanted Lands",["power metal","symphonic metal","progressive metal","neoclassical metal"],["symphonic power","progressive power"],["metal"],[10]], 
        ["Dawn of Victory",["power metal","symphonic metal","progressive metal","neoclassical metal"],["symphonic power","progressive power"],["metal"],[9]], 
        ["Rain of a Thousand Flames",["power metal","symphonic metal","progressive metal","neoclassical metal"],["symphonic power","progressive power"],["metal"],[]], 
        ["Power of the Dragonflame",["power metal","symphonic metal","progressive metal","neoclassical metal"],["symphonic power","progressive power"],["metal"],[]], 
        ["Triumph or Agony",["power metal","symphonic metal","neoclassical metal"],["symphonic power"],["metal"],[]], 
        ["The Frozen Tears of Angels",["power metal","symphonic metal","progressive metal","neoclassical metal"],["symphonic power","progressive power"],["metal"],[]], 
    ],get number() {return this.albums.length},land: "Italy",
},
{   band: "Sepultura",
    albums: [
        ["Beneath the Remains",["thrash metal","death metal"],["old school thrash","thrash-death","old school death metal"],["metal"],[]],             
        ["Arise",["thrash metal"],["old school thrash"],["metal"],[9]],             
        ["Chaos A.D.",["thrash metal","groove metal"],[],["metal"],[]],             
    ],get number() {return this.albums.length},land: "Brazil",
},
{   band: "System Of A Down",
    albums: [
        ["System Of A Down",["alternative metal","avant-garde metal"],["nu metal"],["alternative","metal","avant-garde"],[9]],                                 
        ["Toxicity",["alternative metal","avant-garde metal"],["nu metal"],["alternative","metal","avant-garde"],[9]],                                 
        ["Mezmerize",["alternative metal","avant-garde metal"],["nu metal"],["alternative","metal","avant-garde"],[9]],                                 
        ["Hypnotize",["alternative metal","avant-garde metal"],["nu metal"],["alternative","metal","avant-garde"],[8]],                                 
    ],get number() {return this.albums.length},land: "United States",
},
{   band: "the Beatles",
    albums: [
        ["Revolver",["psychedelic rock","pop rock","psychedelic pop"],[],["rock","pop"],[9]],  
        ["Sgt. Pepper's Lonely Hearts Club Band",["psychedelic rock","pop rock","psychedelic pop","baroque pop"],[],["rock","pop"],[9]],  
        ["Abbey Road",["psychedelic rock","pop rock","psychedelic pop","baroque pop"],[],["rock","pop"],[8]],  
    ],get number() {return this.albums.length},land: "United Kingdom",
},
{   band: "The Doors",
    albums: [
        ["The Doors",["psychedelic rock"],[],["rock"],[9]],  
        ["Strange Days",["psychedelic rock"],[],["rock"],[9]],  
        ["Waiting for the Sun",["psychedelic rock"],[],["rock"],[]],  
        ["The Soft Parade",["psychedelic rock","blues rock"],[],["rock","blues"],[]],  
        ["L.A. Woman",["blues rock","psychedelic rock"],[],["rock","blues"],[10]],  
    ],get number() {return this.albums.length},land: "United States",
},
{   band: "Tool",
    albums: [
        ["Undertow",["alternative metal","progressive metal","progressive rock"],[],["metal","alternative"],[]],  
        ["Lateralus",["alternative metal","progressive metal","progressive rock","post-metal"],[],["metal","alternative","avant-garde"],[9]],  
        ["10,000 Days",["alternative metal","progressive metal","progressive rock","post-metal"],[],["metal","alternative","avant-garde"],[]],  
        ["Fear Inoculum",["alternative metal","progressive metal","progressive rock","post-metal"],[],["metal","alternative","avant-garde"],[10]],  
    ],get number() {return this.albums.length},land: "United States",
},
{   band: "Už Jsme Doma",
    albums: [
        ["Hollywood ",["progressive rock","punk jazz","new wave","experimental rock",],["progressive punk"],["rock","jazz/fusion","avant-garde","punk"],[]], 
    ],get number() {return this.albums.length},land: "Czech",
},
{   band: "Voivod",
    albums: [
        ["War And Pain",["speed metal","thrash metal"],[],["metal"],[9]], 
        ["Rrroooaaarrr",["thrash metal","speed metal"],[],["metal"],[8]], 
        ["Killing Technology",["thrash metal","progressive metal","speed metal","avant-garde metal"],["technical thrash","progressive thrash"],["metal","avant-garde"],[10]], 
        ["dimension hatross",["progressive metal","thrash metal","avant-garde metal"],["technical thrash","progressive thrash"],["metal","avant-garde"],[10]], 
        ["Nothingface",["progressive metal","thrash metal","avant-garde metal"],["technical thrash","progressive thrash"],["metal","avant-garde"],[10]], 
        ["Angel Rat",["progressive metal","psychedelic rock", "progressive rock"],[],["metal","rock"],[9]], 
        ["The Outher Limits",["progressive metal","alternative metal","psychedelic rock","progressive rock"],[],["metal","rock","alternative"],[9]], 
        ["Negatron",["industrial metal","progressive metal","groove metal","thrash metal","avant-garde metal"],["progressive thrash",],["metal","avant-garde","industrial"],[9]], 
        ["Phobos",["industrial metal","progressive metal","groove metal","thrash metal","avant-garde metal","space rock"],["progressive thrash"],["metal","avant-garde","industrial"],[9]], 
        ["Voivod",["heavy metal","progressive metal"],[],["metal"],[6]], 
        ["Katorz",["thrash metal","progressive metal"],["progressive thrash"],["metal"],[6]], 
        ["Infini",["thrash metal","progressive metal"],["progressive thrash"],["metal"],[7]], 
        ["Target Earth",["progressive metal","thrash metal","avant-garde metal"],["progressive thrash"],["metal","avant-garde"],[9]], 
        ["Post Society",["progressive metal","thrash metal","avant-garde metal"],["progressive thrash"],["metal","avant-garde"],[9]], 
        ["The Wake",["progressive metal","thrash metal","avant-garde metal"],["progressive thrash"],["metal","avant-garde"],[10]], 
        ["Synchro Anarchy",["progressive metal","thrash metal","avant-garde metal"],["progressive thrash"],["metal","avant-garde"],[9.5]], 
    ],get number() {return this.albums.length},land: "Canada",
},
]